# Generated by Django 4.1.7 on 2023-04-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newpro', '0003_course_created_user_lesson_created_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Success', models.BooleanField(default=False)),
                ('ErrorCode', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('TerminalKey', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentId', models.CharField(blank=True, max_length=100, null=True)),
                ('OrderId', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('PaymentURL', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('check_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newpro.course', verbose_name='Название курса'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'подписаны'), ('inactive', 'не подписаны')], default='inactive', max_length=15, verbose_name='статус подписки')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newpro.course', verbose_name='курс')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
