# Generated by Django 4.1.7 on 2023-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpro', '0007_remove_subscription_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'подписаны'), ('inactive', 'не подписаны')], default='inactive', max_length=15, verbose_name='статус подписки'),
        ),
    ]
