# Generated by Django 4.1.7 on 2023-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpro', '0008_course_price_alter_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Success', models.BooleanField(default=False)),
                ('ErrorCode', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('TerminalKey', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentId', models.CharField(blank=True, max_length=100, null=True)),
                ('OrderId', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('PaymentURL', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('check_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
